### PR TITLE
[FLINK-16932][legal] Remove unnecessary entries in the distribution jar NOTICE

### PR DESCRIPTION
**Pull request by dianfu**
The following packages which are declared in the NOTICE to be bundled in the jar of statefun-flink-distribution are not actually bundled in it:

org.apache.commons:commons-math3:3.5
commons-cli:commons-cli:jar:1.3.1
commons-collections:commons-collections:3.2.2
org.apache.commons:commons-compress:1.18
com.google.code.findbugs:jsr305:1.3.9
org.objenesis:objenesis:2.1
com.esotericsoftware.kryo:kryo:2.24.0
com.esotericsoftware.minlog:minlog:1.2
This was introduced after https://issues.apache.org/jira/browse/FLINK-16892. 

We should remove these entries in the NOTICE.

### CODE REVIEW

**Comment by dianfu** [comment]
@tzulitai Have submitted a quick PR to address this issue. Could you help to take a look?

**Comment by tzulitai** [comment]
Thanks @dianfu! Good catch.
I've diff-ed RC5 and RC4, and indeed these dependencies are no longer bundled.
Will merge this PR to `master` and `release-2.0`.

**Comment by StephanEwen** [comment]
Taking a look now...

**Comment by StephanEwen** [comment]
Looks correct, merging this...

**Pull request closed without merging**
