### PR TITLE
[hotfix] remove invalid link in README

### PR DESCRIPTION
**Pull request by mingmxu**
`statefun-examples` is not there anymore, remove it from README.

### CODE REVIEW

**Comment by igalshilman** [comment]
Thank you for your contribution @mingmxu,  and welcome aboard :-)

Thats a good catch, indeed we don't have the examples there anymore. But we do have the following repo:

https://github.com/apache/flink-statefun-playground

What do you think about changing the link to point to the playground repo?

**Comment by mingmxu** [comment]
> What do you think about changing the link to point to the playground repo?
That's a good idea. The question is that version of `flink-statefun-playground` is behind. For long term, should we move it back to repo `flink-statefun` to align the snapshot/release version?

**Comment by mingmxu** [comment]
I forgot that `flink-statefun-playground` is included in chapter `Getting Started`, prefer to just remove the line here.

Version of `flink-statefun-playground` is another story ATM.

**Comment by igalshilman** [comment]
Thanks a lot @mingmxu! merged.

**Pull request closed without merging**
